### ISSUE TITLE
Issue with Mindcontrol

### ISSUE THREAD

**Issue by hugopaulsen** [jordonwow/omnibar#15]
If something is used while you are mindcontrolled, it's actually triggering these spell. That's a huge problem for interrupts etc.

Easy fix: check if player is mindcontrolled and if so, only trigger spells from party.

**Comment by jcai1** [comment]
I had the same issue so let me expand here. If you are MC'd then hostilities are reversed. If your arena teammate, or pet, etc. uses a cooldown, it will erroneously be added to the tracking since `sourceFlags` will count as hostile in the combat log event. Conversely, if your opponent uses a cooldown while you are MC'd, it will not get tracked since `sourceFlags` will not count as hostile.
