### ISSUE TITLE
omnibar is not working

### ISSUE THREAD

**Issue by jeremy15553** [jordonwow/omnibar#22]
i was doing an arena on my discipline priest i came out it was glitched i turned it off and turned it back on and its not working i have tried to uninstall the addon and reinstall it but its still not working i was wondering what i could do to fix it

**Comment by zayon007** [comment]
since 8.2 Omnibar is broken i GUEES for everyone
Playng 2v2 and 3v3 and both my partners have the zsame issues, its feels like the tracking is totally random (initially i tought it was like a problem of distance, but after some test it feels like its just broken! i mean, i sit druids and even if i'm on top of them when they use thorns or barskin, the addon doesnt track it! And i'm sure tht i enabled those speells :P)

**Comment by espenja** [comment]
Go to your folder equivalent to this on my computer:
`D:\World of Warcraft\_retail_\WTF\Account\AccountName\SavedVariables`

_Be warned: This will wipe any settings you had in OmniBar, but it will make it appear again_

1. Exit World of Warcraft (Important)
2. Delete `OmniBar.lua` in the folder mentioned above

Hope it works! :)

**Comment by zayon007** [comment]
i already tried to remove the whole addon and reinstall it but nothing
changed, will try this specific actions you said!
Thanks for the reply anywya, have a nice day ^^

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 29 lug 2019 alle ore 23:25 Espen Jacobsson <
notifications@github.com> ha scritto:
